services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P13x13@domain
      PGDATA: /var/lib/postgresql/data

    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "6060:80"
    networks:
      - microservices-net
    restart: unless-stopped


  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo:/data
    environment:
      ## it can also be named this way
      - MONGO_INITDB_ROOT_USERNAME= Piexie
      - MONGO_INITDB_ROOT_PASSWORD= Piexie3
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Piexie
      ME_CONFIG_MONGODB_ADMINPASSWORD: Piexie3
      ME_CONFIG_MONGODB_SERVER: mongodb

  main-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      #for UI
      - "1080:1080"
      #for smtp server
      - "1025:1025"

  ## For kafka configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2081
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres :
  pgadmin:
  mongo: