spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    ## can be camel case also
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/

server:
  port: 8761