spring:
  config:
    import: "classpath:keys.properties"
  datasource:
    url: {db.url.payment}
    username: {db.username.payment}
    password: {db.password.payment}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
