spring:
  config:
    import: "classpath:keys.properties"
  database:
    url: jdbc:postgresql://ep-aged-hat-a4qkgo6f.us-east-1.aws.neon.tech/product?user=neondb_owner
    username: neondb_owner
    password: utTKRQsc6e0F
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "initial"
    baseline-version: 0
    user: ${db.username}
    password: ${db.password}


server:
  port: 8050
